---
# vars file for xpaste
SECRET_KEY_BASE: "secretstring"
RAILS_ENV: "production"
RAILS_LOG_TO_STDOUT: 1
DB_HOST: "127.0.0.1"
DB_PORT: 5432
DB_NAME: "xpastedb"
DB_USER: "xpasteuser"
DB_PASSWORD: "xpastepassword"