---
- name: 'Xpaste install and configuration'
  become: true
  hosts: xpaste
  vars:
    postgres_users_no_log: false # включаем отображение паролей в консоле для отладки, само собой в продакшене это надо выключить

  pre_tasks:
  - name: Update ca-certificates
    yum: name=ca-certificates state=latest

  roles: 
  - geerlingguy.repo-epel
  - geerlingguy.repo-remi
  - geerlingguy.nginx
  - postgres
  - { role: rvm.ruby,
      tags: ruby,
      rvm1_rubies: ['ruby-2.4.2'],
      rvm1_install_flags: '--auto-dotfiles',
      rvm1_install_path: /usr/local/rvm,   
      rvm1_user: root
    }
  - xpaste
  
  tasks:
  - name: "Reload nginx"
    ansible.builtin.service:
      name: "nginx"
      state: "reloaded"